Repository is-project-4th-year/team-profile-site-travellers, pull requests merged in 2025-06, with the labels that each got.

#22 This commit introduces an animal avatar section for Linet Wangui, sho…
  index.html
Labels: enhancement

#24 Commit for avatar addition
  images/eagle 2.jpg
  index.html
Labels: enhancement

#31 External styling
  Documentation.md
  images/blackRhino.jpg
  index.html
Labels: Team profile section

#32 3 styling and layout
  index.html
  styles.css
Labels: Team profile section

#35 docs: Update Documentation for Fancy
  Documentation.md
Labels: documentation

#37 docs: update documentation for Linet
  Documentation.md
Labels: documentation
